#!/usr/bin/env bash
# This script installs nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bkp
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html

sudo service nginx restart
