#!/usr/bin/env bash
# This script installs and configures nginx web server

apt-get -y update
apt-get -y install nginx

service nginx start

echo "Hello World!" > /var/www/html/index.html

text="\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}\n}"
sed -i -r "s/^}$/$text/" /etc/nginx/sites-available/default

nginx -s reload
