#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sed -i "/^\troot/i \ \tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
service nginx restart
