#!/usr/bin/env bash
# This script configures an Ubuntu server with:
# localhost resolved to 127.0.0.2
# facebook.com resolved to 8.8.8.8

file=~/hosts.new
echo -e "127.0.0.2\tlocalhost" > $file
echp -e "8.8.8.8\tfacebook.com" >> $file
cp -f $file /etc/hosts
